name: read_bme280

services:
  influxdb2:
    image: influxdb:2.7.11
    container_name: Influx2
    restart: always
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: dotroniq
      DOCKER_INFLUXDB_INIT_BUCKET: initial_buck

    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token

    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  py_reader:
    build:
      context: ./py_reader
      dockerfile: dockerfile.pyreadbme
    image: pyreader:1.1.0
    container_name: py_readbme
    restart: always
    ports:
      - 9101:9101
    depends_on:
      - influxdb2
    environment:
      INFLUX_URL: http://influxdb2:8086
      INFLUX_TOKEN: /run/secrets/influxdb2-admin-token
      INFLUX_ORG: dotroniq
      INFLUX_BUCKET: initial_buck
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/i2c-2:/dev/i2c-2"
      # General propuse IO
      - /dev/gpiomem:/dev/gpiomem
      # PMW
      - /dev/vcio:/dev/vcio
      # Para componente ADS MCP3008
      #- /dev/spidev0.0:/dev/spidev0.0
      #- /dev/spidev0.1:/dev/spidev0.1
      #priviliged: True
    cap_add:
      - SYS_RAWIO
    volumes:
      - /sys/class/thermal:/sys/class/thermal:ro

  grafana:
    image: grafana/grafana-enterprise:11.6.0
    container_name: Grafanadev1
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: Prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus_cfg/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

secrets:
  influxdb2-admin-username:
    file: ./.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./.env.influxdb2-admin-token
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-data:
  prometheus_data: