name: read_bme280

services:
  py_reader:
    build:
      context: .
      dockerfile: dockerfile.pyreadbme
    image: pyreader:1.0.0
    container_name: py_readbme
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/i2c-2:/dev/i2c-2"
    #priviliged: True
    cap_add:
      - SYS_RAWIO
